Fix / migration to delete bedienaren
lblod/app-organization-portal pull request #215
Opened 2023-01-18 14:44 UTC by iurianu

OP-2043 - Delete "Bedienaren" from worship service in Production.
OP-2047 - Delete a bedienaar from OP in Production

2023-01-18 17:23 UTC, claire-lovisa requested changes
I see two issues here:
- The positions have contact points attached, they also need to be deleted
- I don't get why you say that a curl call isn't needed, as you can see in the screenshot below the deleted positions still appear in the Personen view ?

![Capture d’écran du 2023-01-18 18-15-32](https://user-images.githubusercontent.com/23281659/213251126-56cbf2d1-cc65-4552-af5b-6f77315de863.png)

2023-01-19 11:18 UTC, claire-lovisa requested changes
The contact points have addresses that also need to be deleted. You should check all the data you're removing before creating the PR, to ensure you remove all the necessary parts.

The curl calls are not working, the subjects should be predicates, the predicates should be objects and the objects should be subjects. I suggest that you first setup the app so that you can see the persons in the `Personen` page, then test the curl calls to ensure they work before asking for review.

2023-01-20 16:29 UTC, claire-lovisa requested changes

2023-01-20 16:29 UTC, claire-lovisa commented on config/migrations/2023/20230120150000-delete-bedienaren-from-worship-service.sparql
> +    ?functie ?pFunctie ?oFunctie .
Those two should not be deleted, they are shared with other positions

2023-01-23 09:58 UTC, claire-lovisa commented
I also think that the curl call should be as followed, because it doesn't work with the current one
```
curl --location --request POST '172.19.0.30/update' \
--header 'Content-Type: application/vnd.api+json' \
--data-raw ' [
  {
    "deletes": [
      {
        "subject": { "type": "uri", "value": "http://data.lblod.info/id/rollenBedienaar/6332F770036B579F0A26FF2F" },
        "predicate": { "type": "uri", "value": "http://www.w3.org/ns/org#heldBy" },
        "object": { "type": "uri", "value": "http://data.lblod.info/id/personen/6332F6FD036B579F0A26FF2B" }
      },
      {
        "subject": { "type": "uri", "value": "http://data.lblod.info/id/rollenBedienaar/6332F6C9036B579F0A26FF2A" },
        "predicate": { "type": "uri", "value": "http://www.w3.org/ns/org#heldBy" },
        "object": { "type": "uri", "value": "http://data.lblod.info/id/personen/6332F648036B579F0A26FF26" }
      },
      {
        "subject": { "type": "uri", "value": "http://data.lblod.info/id/rollenBedienaar/6332F7FB036B579F0A26FF34" },
        "predicate": { "type": "uri", "value": "http://www.w3.org/ns/org#heldBy" },
        "object": { "type": "uri", "value": "http://data.lblod.info/id/personen/6332F7AF036B579F0A26FF30" }
      },
      {
        "subject": { "type": "uri", "value": "http://data.lblod.info/id/rollenBedienaar/638F083FA742F4FD4AB55907" },
        "predicate": { "type": "uri", "value": "http://www.w3.org/ns/org#heldBy" },
        "object": { "type": "uri", "value": "http://data.lblod.info/id/personen/638F07A6A742F4FD4AB55903" }
      }
    ],
    "inserts": []
  }
]'
```

2023-01-24 14:17 UTC, bdevloed commented
@iurianu / @claire-lovisa migration and curl work as expected. The positions are indeed removed.

2023-01-25 11:09 UTC, merged