Fix dev mandatarissen without persons
lblod/app-organization-portal pull request #353
Opened 2023-11-25 07:47 UTC by claire-lovisa

OP-2868

Allows dev to display its data properly before we do a proper fix of the consumer

This migration needs to be followed by a reindex

2023-11-25 14:36 UTC, mirdono commented
The inclusion of the `?mandaat a ?type` triple in the `WHERE` clause causes this migrations to miss a number of imo relevant entries. The following query returns 8717 results after executing the migration on a DB that was freshly synced with remote DEV.
```
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
SELECT (COUNT (DISTINCT ?mandaat) AS ?count)
  FROM <http://mu.semte.ch/graphs/administrative-unit>
  FROM <http://mu.semte.ch/graphs/worship-service>
  WHERE {
    ?mandaat mandaat:isBestuurlijkeAliasVan ?person .
    FILTER NOT EXISTS { ?person ?p ?o . }
  }
```

2023-11-25 14:38 UTC, mirdono requested changes
The inclusion of the `?mandaat a ?type` triple in the WHERE clause causes this migrations to miss a number of imo relevant entries. The following query returns 8717 results after executing the migration on a DB that was freshly synced with remote DEV.
```
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
SELECT (COUNT (DISTINCT ?mandaat) AS ?count)
  FROM <http://mu.semte.ch/graphs/administrative-unit>
  FROM <http://mu.semte.ch/graphs/worship-service>
  WHERE {
    ?mandaat mandaat:isBestuurlijkeAliasVan ?person .
    FILTER NOT EXISTS { ?person ?p ?o . }
  }
```

2023-11-26 09:20 UTC, claire-lovisa commented
@mirdono I added a second step to the migration that removes the mandatarissen without a type !

2023-11-26 12:49 UTC, mirdono approved these changes

2023-11-27 06:31 UTC, merged